//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manage_Seasonal_Tires.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Manage_Seasonal_Tires.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManageSeasonalTires.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Customer.
        /// </summary>
        public static string btn_addcust {
            get {
                return ResourceManager.GetString("btn_addcust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string btn_addvehicle {
            get {
                return ResourceManager.GetString("btn_addvehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-Out.
        /// </summary>
        public static string btn_checkout {
            get {
                return ResourceManager.GetString("btn_checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Customer.
        /// </summary>
        public static string btn_deleteCust {
            get {
                return ResourceManager.GetString("btn_deleteCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string btn_replace {
            get {
                return ResourceManager.GetString("btn_replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Details of the Customer.
        /// </summary>
        public static string cdetails {
            get {
                return ResourceManager.GetString("cdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string dob {
            get {
                return ResourceManager.GetString("dob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string fdirection {
            get {
                return ResourceManager.GetString("fdirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Customer Name to Filter.
        /// </summary>
        public static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string fname {
            get {
                return ResourceManager.GetString("fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lname {
            get {
                return ResourceManager.GetString("lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement Date.
        /// </summary>
        public static string replaceDate {
            get {
                return ResourceManager.GetString("replaceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string storage {
            get {
                return ResourceManager.GetString("storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Location.
        /// </summary>
        public static string storagelocation {
            get {
                return ResourceManager.GetString("storagelocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement History of the Customer.
        /// </summary>
        public static string Tbk_replaceHistory {
            get {
                return ResourceManager.GetString("Tbk_replaceHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tire Category.
        /// </summary>
        public static string tcategory {
            get {
                return ResourceManager.GetString("tcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Tires.
        /// </summary>
        public static string tnumber {
            get {
                return ResourceManager.GetString("tnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Customer and Click here to Add his Tires.
        /// </summary>
        public static string tooltip_add {
            get {
                return ResourceManager.GetString("tooltip_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here to Add a New Customer.
        /// </summary>
        public static string tooltip_Btn_addCust {
            get {
                return ResourceManager.GetString("tooltip_Btn_addCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Customer and Click here to Delete.
        /// </summary>
        public static string tooltip_Btn_deleteCust {
            get {
                return ResourceManager.GetString("tooltip_Btn_deleteCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Vehicle and Click here to Check-Out the Tires.
        /// </summary>
        public static string tooltip_delete {
            get {
                return ResourceManager.GetString("tooltip_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Vehicle and Click here to Replace Tires.
        /// </summary>
        public static string tooltip_replace {
            get {
                return ResourceManager.GetString("tooltip_replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Vehicle Details.
        /// </summary>
        public static string vdetails {
            get {
                return ResourceManager.GetString("vdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Model.
        /// </summary>
        public static string vmodel {
            get {
                return ResourceManager.GetString("vmodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Number.
        /// </summary>
        public static string vnumber {
            get {
                return ResourceManager.GetString("vnumber", resourceCulture);
            }
        }
    }
}
